### ISSUE TITLE
Warning: Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by satelllte** [oven-sh/setup-bun#51] opened 2024-01-27 12:48 UTC
This is the annotation warning I started to receive when using `oven-sh/setup-bun@v1` action:

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: oven-sh/setup-bun@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

**Comment by xhyrom** [comment] 2024-01-27 16:39
Duplicate of https://github.com/oven-sh/setup-bun/issues/50

For now, use v1.1.1

**Closed as not planned by xhyrom** 2024-01-27 16:39 UTC
Labels: duplicate
