### ISSUE TITLE
How to cache "bun global cache" on pipeline?

### ISSUE THREAD

**Issue by itsgitz** [oven-sh/setup-bun#48] opened 2024-01-06 08:39 UTC
Hello!

According to this documentation https://bun.sh/docs/install/cache, **Bun** stores all downloaded packages from the registry in a global cache at `~/.bun/install/cache`. I want to cache the downloaded packages (global cache) like https://github.com/actions/setup-node#caching-global-packages-data to speed up my workflows. Does **Bun** handle this by default? Or should I create/store the global cache using [actions/cache](https://github.com/actions/cache)?

**Comment by Morzaram** [comment] 2024-01-10 18:44
I'm not sure but does this thread help?
https://github.com/oven-sh/setup-bun/issues/14

**Comment by xhyrom** [comment] 2024-01-11 15:51
This is duplicate of https://github.com/oven-sh/setup-bun/issues/14. If you want to cache dependencies, you can do it using [actions/cache](https://github.com/actions/cache) for now.

**Closed as not planned by xhyrom** 2024-01-11 15:51 UTC
Labels: duplicate
