### ISSUE TITLE
Windows 404 error

### ISSUE THREAD

**Issue by 0xmemorygrinder** [oven-sh/setup-bun#69] opened 2024-03-21 16:18 UTC
Hello,

I use setup-bun action in one of my workflow and it fails with a 404 error on the download link in windows environment.

I know this issue has already been filed but it has been marked as resolve even if the problem still persist or reappeared.

Thank you in advance for your answer

**Comment by xhyrom** [comment] 2024-03-21 16:39
Duplicate of https://github.com/oven-sh/setup-bun/issues/22

**Closed as not planned by xhyrom** 2024-03-21 16:39 UTC
