### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by MickL** [oven-sh/setup-bun#54] opened 2024-01-31 23:15 UTC
Pipelines throw the following warning:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: oven-sh/setup-bun@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Can we update setup-bun to use Node 20?

**Comment by jerryc05** [comment] 2024-02-01 03:42
same warning on my end, but the repo's `action.yml` is using node 20 already.
https://github.com/oven-sh/setup-bun/blob/94177e527c40bdaeca682f116e326979df067c2a/action.yml#L25

**Comment by xhyrom** [comment] 2024-02-03 07:38
Duplicate of https://github.com/oven-sh/setup-bun/issues/50

**Closed as not planned** 2024-02-03 07:39 UTC
Labels: duplicate
