### ISSUE TITLE
Error: Unexpected HTTP response: 404

### ISSUE THREAD

**Issue by SurajRaika** [oven-sh/setup-bun#44] opened 2023-12-25 10:25 UTC
![image](https://github.com/oven-sh/setup-bun/assets/103476230/6b5a7c9e-e0fc-45b8-9090-e6d942f5990e)
look like 
[https://bun.sh/download/latest/win32/x64?avx2=true&profile=false ](https://bun.sh/download/latest/win32/x64?avx2=true&profile=false )

 
 
 zip file is not present in assets! , 

so  I have to use previous version other  then bun-v1.0.20  for now

**Comment by PabloSzx** [comment] 2024-01-02 22:46
I think windows support just comes down to https://github.com/oven-sh/bun/issues/43

**Comment by xhyrom** [comment] 2024-01-03 13:56
Duplicate of https://github.com/oven-sh/setup-bun/issues/22

**Closed as not planned by xhyrom** 2024-01-03 13:56 UTC
